2019-08-03 19:36:58 WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password
2019-08-03 19:36:58 WARNING (MainThread) [homeassistant.components.http.auth] legacy_api_password support has been enabled.
2019-08-03 19:37:03 WARNING (MainThread) [homeassistant.components.mqtt] Data in your config entry is going to override your configuration.yaml: {'broker': '192.168.1.105', 'discovery': True, 'port': 1883}
2019-08-03 19:56:39 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:56:44 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:56:45 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:56:48 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:56:49 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:56:52 ERROR (SyncWorker_2) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:56:52 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:56:52 ERROR (SyncWorker_15) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:56:56 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:56:57 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:00 ERROR (SyncWorker_12) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:01 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:04 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:05 ERROR (SyncWorker_3) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:08 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:10 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:14 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:14 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:57:17 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:18 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:57:21 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:22 ERROR (SyncWorker_5) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:23 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:25 ERROR (SyncWorker_4) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:27 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:30 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:34 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:36 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:38 ERROR (SyncWorker_13) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:40 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:43 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:44 ERROR (SyncWorker_19) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 19:57:47 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:57:47 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:49 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:51 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:57:53 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:54 ERROR (SyncWorker_19) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:57:56 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:57:57 ERROR (SyncWorker_3) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:58:00 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:02 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:06 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:09 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:10 ERROR (SyncWorker_6) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 19:58:13 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:15 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:16 ERROR (SyncWorker_4) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 19:58:18 ERROR (SyncWorker_4) [homeassistant.components.life360.device_tracker] get_circle_members "Family": OK again
2019-08-03 19:58:19 ERROR (SyncWorker_9) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 19:58:25 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:58:28 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 19:58:28 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 19:58:31 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:39 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:42 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:45 WARNING (SyncWorker_7) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:46 ERROR (SyncWorker_6) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:15:49 WARNING (SyncWorker_7) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:52 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:53 ERROR (SyncWorker_7) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:15:56 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:15:58 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:00 ERROR (SyncWorker_12) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:16:02 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:05 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:06 ERROR (SyncWorker_2) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:16:09 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:11 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:13 ERROR (SyncWorker_9) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:16:18 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:22 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:24 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:27 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:31 ERROR (SyncWorker_3) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:16:31 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:35 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:37 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:41 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:44 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:45 ERROR (SyncWorker_1) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:16:46 ERROR (SyncWorker_17) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:16:49 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:16:49 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:53 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:16:53 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:16:57 ERROR (SyncWorker_17) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:16:57 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:01 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:02 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:05 ERROR (SyncWorker_13) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:17:06 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:10 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:14 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:15 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:18 ERROR (SyncWorker_14) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:17:19 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:23 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:27 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:28 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:30 ERROR (SyncWorker_1) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:17:33 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:35 ERROR (SyncWorker_16) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:17:37 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:38 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:40 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:41 ERROR (SyncWorker_1) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:17:41 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:45 ERROR (SyncWorker_16) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:17:47 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:49 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:50 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:53 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:17:53 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:17:56 ERROR (SyncWorker_0) [homeassistant.components.life360.device_tracker] get_circle_members "Family": OK again
2019-08-03 20:17:57 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:18:01 ERROR (SyncWorker_15) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:02 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:05 WARNING (SyncWorker_14) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:06 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:18:09 ERROR (SyncWorker_14) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:10 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:18:28 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:31 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:31 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:34 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:35 ERROR (SyncWorker_16) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:38 ERROR (SyncWorker_17) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:41 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:44 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:45 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:48 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:49 ERROR (SyncWorker_5) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:52 ERROR (SyncWorker_13) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:18:54 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:57 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:18:58 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:01 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:07 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:10 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:11 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:13 ERROR (SyncWorker_10) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:19:14 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:16 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:20 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:20 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:22 ERROR (SyncWorker_17) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:19:24 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:28 ERROR (SyncWorker_16) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:19:35 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:36 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:39 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:40 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:19:43 ERROR (SyncWorker_9) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:19:44 ERROR (SyncWorker_11) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:19:46 WARNING (SyncWorker_8) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:49 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:49 WARNING (SyncWorker_8) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:53 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:19:53 ERROR (SyncWorker_8) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:19:57 ERROR (SyncWorker_15) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:19:59 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:02 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:03 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:06 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:10 ERROR (SyncWorker_4) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:20:12 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:15 ERROR (SyncWorker_5) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:20:15 WARNING (SyncWorker_17) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:18 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 20:20:19 ERROR (SyncWorker_17) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:20:25 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:28 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:28 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:32 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 20:20:32 ERROR (SyncWorker_13) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 20:20:38 ERROR (SyncWorker_14) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 20:20:43 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:20:36 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:39 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:42 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:43 ERROR (SyncWorker_11) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:20:46 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:49 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:50 ERROR (SyncWorker_4) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:20:53 WARNING (SyncWorker_19) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:55 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:20:57 ERROR (SyncWorker_19) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:20:59 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:02 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:03 ERROR (SyncWorker_5) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:21:06 WARNING (SyncWorker_15) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:08 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:12 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:15 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:19 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:21 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:25 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:28 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:32 ERROR (SyncWorker_9) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 21:21:33 ERROR (SyncWorker_1) [homeassistant.components.life360.device_tracker] get_circles: OK again
2019-08-03 21:21:35 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:36 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:39 WARNING (SyncWorker_9) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:40 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:41 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:43 ERROR (SyncWorker_9) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:21:44 ERROR (SyncWorker_1) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:21:45 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:46 WARNING (SyncWorker_7) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:49 ERROR (SyncWorker_10) [homeassistant.components.life360.device_tracker] get_circles: CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:21:50 WARNING (SyncWorker_7) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:55 WARNING (SyncWorker_7) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:56 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:21:59 WARNING (SyncWorker_18) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:21:59 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:22:03 WARNING (SyncWorker_18) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:22:03 ERROR (SyncWorker_6) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:22:09 ERROR (SyncWorker_14) [homeassistant.components.life360.device_tracker] get_circle_members "Family": OK again
2019-08-03 21:22:09 WARNING (SyncWorker_18) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:22:13 WARNING (SyncWorker_18) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:22:13 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:22:17 ERROR (SyncWorker_18) [homeassistant.components.life360.device_tracker] get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:22:17 WARNING (SyncWorker_11) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members
2019-08-03 21:22:20 WARNING (SyncWorker_16) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)")': /v3/circles.json
2019-08-03 21:22:21 ERROR (SyncWorker_11) [homeassistant.components.life360.device_tracker] Suppressing further errors until OK: get_circle_members "Family": CommError: HTTPSConnectionPool(host='api.life360.com', port=443): Max retries exceeded with url: /v3/circles/9299cb9b-62b2-4e75-b08d-fa5d3b74af54/members (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=3.05)"))
2019-08-03 21:22:26 ERROR (SyncWorker_19) [homeassistant.components.life360.device_tracker] get_circle_members "Family": OK again
